const CartActionTypes = {
  TOGGLE_CART: "TOGGLE_CART",
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  REMOVE_ITEM_FROM_CART: "REMOVE_ITEM_FROM_CART",
  CLEAR_CART: "CLEAR_CART",
  INIT_CART_FROM_FIREBASE: "INIT_CART_FROM_FIREBASE",
  PERSIST_CART_TO_FIREBASE: "PERSIST_CART_TO_FIREBASE"
};

export default CartActionTypes;
