const CartActionTypes = {
  TOGGLE_CART: "TOGGLE_CART",
  ADD_ITEM: "ADD_ITEM",
  REMOVE_ITEM: "REMOVE_ITEM",
  REMOVE_ITEM_FROM_CART: "REMOVE_ITEM_FROM_CART",
  CLEAR_CART: "CLEAR_CART",
<<<<<<< HEAD
  SET_CART_FROM_FIREBASE: "SET_CART_FROM_FIREBASE",
  UPDATE_CART_IN_FIREBASE: "UPDATE_CART_IN_FIREBASE"
=======
  INIT_CART_FROM_FIREBASE: "INIT_CART_FROM_FIREBASE",
  PERSIST_CART_TO_FIREBASE: "PERSIST_CART_TO_FIREBASE"
>>>>>>> 0bd0abb6b6be55983f7d0217016c9453c649fc3c
};

export default CartActionTypes;
